services:
  mono_gs:
    container_name: mono_gs_container
    build:
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1007}
        - GID=${GID:-1007}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    network_mode: "host"
    tty: true
    volumes:
        # - /home/haedamoh/logs/:/home/docker_dev/logs/
        - /home/shared/:/home/docker_dev/shared/ 
        - /home/haedamoh/git/MonoGS/:/home/docker_dev/MonoGS/
        - /home/haedamoh/.netrc:/home/docker_dev/.netrc
        - /home/haedamoh/.git:/home/docker_dev/.git 
        - /home/haedamoh/logs/:/home/docker_dev/logs
    # command: python /home/docker_dev/silvr/train.py
    image: silvr:latest 
    